# Generated by Django 5.2.11 on 2026-03-06 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThoughtPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(blank=True, choices=[('student', 'Student'), ('company', 'Company')], max_length=20)),
                ('title', models.CharField(help_text='Job Role Interested / Hiring For', max_length=255)),
                ('description', models.TextField()),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='thought_resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
