# Generated by Django 5.2.11 on 2026-03-06 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thoughtpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_thoughts', to=settings.AUTH_USER_MODEL),
        ),
    ]
