# Generated by Django 5.2.11 on 2026-03-05 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('overall_score', models.IntegerField()),
                ('classification', models.CharField(max_length=100)),
                ('recommendation', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume Evaluation',
                'verbose_name_plural': 'Resume Evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
