# Generated by Django 5.2.11 on 2026-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_useractivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='is_used',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='user',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
