# Generated by Django 5.2.11 on 2026-03-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_useractivity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
