# Generated by Django 5.2.11 on 2026-03-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='yearly', max_length=20),
        ),
    ]
