# Generated by Django 5.2.11 on 2026-02-28 00:27

import apps.companies.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_type', models.CharField(max_length=100)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(max_length=32, unique=True)),
                ('cin_number', models.CharField(max_length=32, unique=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('incorporation_certificate', models.FileField(blank=True, null=True, upload_to=apps.companies.models.company_document_upload_path)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to=apps.companies.models.company_document_upload_path)),
                ('founder_id_proof', models.FileField(blank=True, null=True, upload_to=apps.companies.models.company_document_upload_path)),
                ('registration_proof', models.FileField(blank=True, null=True, upload_to=apps.companies.models.company_document_upload_path)),
                ('admin_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_company_email')],
            },
        ),
    ]
