# Generated by Django 5.2.11 on 2026-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
